# 定义默认网络
networks:
  default:
    name: registry-net
    driver: bridge

services:
  ## docker hub
  dockerhub:
    container_name: reg-docker-hub
    image: dqzboy/registry:latest
    restart: always
    environment:
      - OTEL_TRACES_EXPORTER=none
      #- http=http://host:port
      #- https=http://host:port
    volumes:
      - /root/acap.cc/reg-docker/registry:/var/lib/registry
      - /root/acap.cc/registry-hub.yml:/etc/distribution/config.yml
      - /root/acap.cc/htpasswd:/auth/htpasswd
    ports:
      - 51000:5000

  ## UI
  registry-ui:
    container_name: registry-ui
    image: dqzboy/docker-registry-ui:latest
    environment:
      - DOCKER_REGISTRY_URL=http://reg-docker-hub:5000
      # [必须]使用 openssl rand -hex 16 生成唯一值
      - SECRET_KEY_BASE=548e60b20ab59aeec794bd2d0f30d40c
      # 启用Image TAG 的删除按钮
      - ENABLE_DELETE_IMAGES=true
      - NO_SSL_VERIFICATION=true
    restart: always
    ports:
      - 50000:8080


  githubProxy:
    image: hanzhichen/github-proxy-go:latest
    platform: linux/arm64
    container_name: githubProxy
    ports:
      - "0.0.0.0:60000:80"
    env_file:
      - /lab/envs/githubproxy-go.env
    restart: always

  uptime-kuma:
    image: louislam/uptime-kuma:1
    container_name: uptime-kuma
    restart: always
    ports:
      - "127.0.0.1:3001:3001"
    volumes:
      - /root/acap.cc/uptime:/app/data


  # ## ghcr.io
  # ghcr:
  #   container_name: reg-ghcr
  #   image: dqzboy/registry:latest
  #   restart: always
  #   environment:
  #     - OTEL_TRACES_EXPORTER=none
  #     #- http=http://host:port
  #     #- https=http://host:port
  #   volumes:
  #     - ./registry/data:/var/lib/registry
  #     - ./registry-ghcr.yml:/etc/distribution/config.yml
  #     #- ./htpasswd:/auth/htpasswd
  #   ports:
  #     - 52000:5000

  # ## gcr.io
  # gcr:
  #   container_name: reg-gcr
  #   image: dqzboy/registry:latest
  #   restart: always
  #   environment:
  #     - OTEL_TRACES_EXPORTER=none
  #     #- http=http://host:port
  #     #- https=http://host:port
  #   volumes:
  #     - ./registry/data:/var/lib/registry
  #     - ./registry-gcr.yml:/etc/distribution/config.yml
  #     #- ./htpasswd:/auth/htpasswd
  #   ports:
  #     - 53000:5000

  # ## k8s.gcr.io
  # k8sgcr:
  #   container_name: reg-k8s-gcr
  #   image: dqzboy/registry:latest
  #   restart: always
  #   environment:
  #     - OTEL_TRACES_EXPORTER=none
  #     #- http=http://host:port
  #     #- https=http://host:port
  #   volumes:
  #     - ./registry/data:/var/lib/registry
  #     - ./registry-k8sgcr.yml:/etc/distribution/config.yml
  #     #- ./htpasswd:/auth/htpasswd
  #   ports:
  #     - 54000:5000

  # ## registry.k8s.io
  # k8s:
  #   container_name: reg-k8s
  #   image: dqzboy/registry:latest
  #   restart: always
  #   environment:
  #     - OTEL_TRACES_EXPORTER=none
  #     #- http=http://host:port
  #     #- https=http://host:port
  #   volumes:
  #     - ./registry/data:/var/lib/registry
  #     - ./registry-k8s.yml:/etc/distribution/config.yml
  #     #- ./htpasswd:/auth/htpasswd
  #   ports:
  #     - 55000:5000

  # ## quay.io
  # quay:
  #   container_name: reg-quay
  #   image: dqzboy/registry:latest
  #   restart: always
  #   environment:
  #     - OTEL_TRACES_EXPORTER=none
  #     #- http=http://host:port
  #     #- https=http://host:port
  #   volumes:
  #     - ./registry/data:/var/lib/registry
  #     - ./registry-quay.yml:/etc/distribution/config.yml
  #     #- ./htpasswd:/auth/htpasswd
  #   ports:
  #     - 56000:5000

  # ## mcr.microsoft.com
  # mcr:
  #   container_name: reg-mcr
  #   image: dqzboy/registry:latest
  #   restart: always
  #   environment:
  #     - OTEL_TRACES_EXPORTER=none
  #     #- http=http://host:port
  #     #- https=http://host:port
  #   volumes:
  #     - ./registry/data:/var/lib/registry
  #     - ./registry-mcr.yml:/etc/distribution/config.yml
  #     #- ./htpasswd:/auth/htpasswd
  #   ports:
  #     - 57000:5000

  # ## docker.elastic.co
  # elastic:
  #   container_name: reg-elastic
  #   image: dqzboy/registry:latest
  #   restart: always
  #   environment:
  #     - OTEL_TRACES_EXPORTER=none
  #     #- http=http://host:port
  #     #- https=http://host:port
  #   volumes:
  #     - ./registry/data:/var/lib/registry
  #     - ./registry-elastic.yml:/etc/distribution/config.yml
  #     #- ./htpasswd:/auth/htpasswd
  #   ports:
  #     - 58000:5000

  # ## nvcr.io
  # nvcr:
  #   container_name: reg-nvcr
  #   image: dqzboy/registry:latest
  #   restart: always
  #   environment:
  #     - OTEL_TRACES_EXPORTER=none
  #     #- http=http://host:port
  #     #- https=http://host:port
  #   volumes:
  #     - ./registry/data:/var/lib/registry
  #     - ./registry-nvcr.yml:/etc/distribution/config.yml
  #     #- ./htpasswd:/auth/htpasswd
  #   ports:
  #     - 59000:5000
